name: Build Snip (C++ CMake)

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Copy binary
        run: |
          copy build\Release\snipx64.exe snipx64.exe

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: snipx64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
